# VirtualCard [/api/v1.0/virtualcard/issue]

## VirtualCard [POST]

+ Request virtualcardRequest (application/json)

    + Headers
      cnx-tenantid: stgLoyalty
      cnx-environment-token: SG
      cnx-userip: 10.79.40.228
      Content-Type: application/json
      clientId: 103

    + Attributes (virtualcardRequest)

+ Response 200 (application/json)

    + Attributes (virtualcardResponse)