## cardInfo

+ id:`1371` (string,required)

+ cardHolderName:`Adam Smith` (string,required)

+ number:`111111******5705` (string,required)

+ token:'~$^383f5090-c935-4a04-a539-4d89be8b3e54|ZGVmYXVsdA==|ZGVmYXVsdA==~$^' (string,required)

+ issuedBy: `VI` (enum)
  + VI
  + CA
+ isGlobalVirtualCreditCard:`false` (boolean,optional)

+ description:`This card is governed by Chase bank's Terms and Conditions` (string,optional)

+ cvv:`617` (string,required)

+ expiryDate:`2021-12-13` (string,required)

+ activationDate:`2021-12-13` (string,optional)

+ billingAddress (billingAddressInfo,optional)

+ createdBy:`Online` (string,required)

+ createdAtUtc:`2020-03-16T03:33:20.8753218Z` (string,required)
