## metadataInfo (array,fixed-type)
 + (object)
  + key: ReconciliationId (string)
  + value: CA023192 (string)
 + (object)
  + key: CardType (string)
  + value: 3 (string)
 + (object)
  + key: TransitCode (string)
  + value: d30af210-305c-4f86-a6c4-d922ef3327f5 (string)