## productDataInfo

+ type: 'Cruise' (enum)
  + Flight
  + Activity
  + Car
  + Cruise
  + Hotel
  + Insurance
  + Tours

+ supplier: `Travelport` (string,optional)

+ isDomesticSupplier: `true` (boolean,required)

+ vendor (vendorInfo,optional)
