## virtualcardResponse

+ card (cardInfo,required)

+ cardSpecifications (cardSpecificationsInfo,required)

+ productData (productDataInfo,optional)

+ metadata (array [metadataInfo],fixed-type,optional)