## virtualcardRequest

+ pointOfSaleId:`4tjwk2lt4ox` (string,required) - POS or Point of Sale refers to the end point from where the customers interact with the system

+ currency:`USD` (string,required)

+ customer (customerInfo,optional)

+ cardSpecifications (cardSpecificationsInfo,required)

+ productData (productDataInfo,optional)

+ lastCardIdToSkip:`1kd279293uv5` (string,optional)

+ metadata (metadataInfo, optional)