openapi: 3.0.1
info:
  title: Dr3
  x-cortex-git:
    github:
      repository: TaviscaSolutions/DR3
  x-cortex-tag: dr3
  x-cortex-type: service
  x-cortex-owners:
     - type: EMAIl
       email: cloud9_tribe@tavisca.com
     - name: cloud9
       type: GROUP
